name = "visibuy-frontend"  # Your worker name
type = "javascript"         # Change to "webpack" if using a bundler
account_id = "2d02085f50d5cf205339cfc842eeb976"  # Replace with your Cloudflare account ID
workers_dev = true
compatibility_date = "2024-09-22"  # Update this to your deployment date

[build]
command = "npm run build"  # Your build command
node_version = "18.18.0"    # Specify the required Node version
pages_build_output_dir = "dist"  # Set the output directory for your build

[env.staging]
# Staging settings
name = "visibuy-frontend-staging"
# Other staging-specific settings

[env.production]
# Production settings
name = "visibuy-frontend-production"
# Other production-specific settings
